### PR TITLE
Add sourcemap support for tests

### PR DESCRIPTION
**Pull request by gregarndt**

### CODE REVIEW

**Comment by imbstack** [comment]
r+

**Comment by gregarndt** [comment]
Thank you sir!

**Comment by imbstack** [comment]
Ok, this is where this sort of thing gets confusing. I think if you add `babel-plugin-source-map-support` and it is being used, then all of the compiled code in production will try to import source-map-support. Since it's been added to your dependencies, this should be ok, but I think at the moment `babel-plugin-source-map-support` is doing nothing here. It would seem to me that a `.babelrc` that asks to extend `babel-preset-taskcluster` and also uses  `babel-plugin-source-map-support` would do the trick, but I'm not sure. I think that as things stand, you could remove that package from here and it would still work for development only, while not messing with prod.

**Comment by gregarndt** [comment]
I tested these changes out in prod earlier and it seemed to not break things as they are, but I like the idea of maybe incorporating them into a babelrc but isn't that defeating the purpose of using our own babel plugin?

**Comment by gregarndt** [comment]
So basically the question is, in a world where we are using the taskcluster presets when compiling, how do we enable source map support for both production code and tests?

**Pull request merged**
